### ISSUE TITLE
Use Iterators.reverse

### ISSUE THREAD

**Issue by mcmcgrath13** [JuliaServices/Rematch2.jl#54]
https://github.com/JuliaServices/Rematch2.jl/blob/678a408b859cfc042d58cb7c02d7189e6cd6a4fb/src/TopologicalSort.jl#L30

This doesn't need to copy the vector, so use the lazy `Iterators.reverse` instead

**Comment by gafter** [comment]
Fixed in #43:

```julia
using Base.Iterators: reverse
```
